
name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0,20 12,0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
    #  - uses: anmol098/waka-readme-stats@master
    #     COMMIT_BY_ME: true
      - uses: athul/waka-readme@v0.1.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
          SHOW_TITLE: true         
